import type { LucideIcon } from "lucide-react";
import {
  FileText,
  Scissors,
  Minimize2,
  FileImage,
  Images,
  ImageDown,
  Scaling,
  Repeat,
  Crop,
  Info,
  Braces,
  Minimize,
  Binary,
  Fingerprint,
  Clock,
  QrCode,
  KeyRound,
  Type,
  Percent,
  CalendarDays,
  Droplets,
  Baby,
  Activity,
  GraduationCap,
  Code2,
  Quote,
  Target,
  CaseSensitive,
  BookOpen,
  ScanSearch,
  HeartHandshake,
  ShoppingBasket,
  FileSpreadsheet,
  Receipt,
  CreditCard,
  Award,
  MapPin,
  Egg,
  Flame,
  Link2,
  Link,
  Contrast,
  AppWindow,
  AlignLeft,
  Bot,
  Timer,
  Shuffle,
  Sparkles,
  Library,
} from "lucide-react";
import type { CategoryId } from "./categories";

/**
 * The light index for one tool: everything needed to list it, search it and
 * route to it, and nothing more.
 *
 * The explanatory copy and FAQ live in `lib/tool-content.ts` instead, because
 * the client-side search imports this module and anything here ships to the
 * browser.
 */
export interface Tool {
  id: string;
  name: string;
  slug: string;
  /** One line, used on cards and in search. */
  description: string;
  category: CategoryId;
  icon: LucideIcon;
  tags: string[];
  featured?: boolean;
  popular?: boolean;
  isNew?: boolean;
  /** `live` tools have a working component; `soon` renders a clear placeholder. */
  status: "live" | "soon";
  /** True when the file never leaves the device, so we only claim it where true. */
  localProcessing?: boolean;
  /** Sort key for "New" ordering; higher is newer. */
  addedAt: number;
}

export const TOOLS: Tool[] = [
  /* ---------------------------------------------------------------- PDF */
  {
    id: "merge-pdf",
    name: "Merge PDF",
    slug: "merge-pdf",
    description: "Combine several PDF files into one document.",
    category: "pdf",
    icon: FileText,
    tags: ["pdf", "merge", "combine", "join", "documents"],
    popular: true,
    status: "live",
    localProcessing: true,
    addedAt: 1,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    slug: "split-pdf",
    description: "Extract a page range from a PDF into a new file.",
    category: "pdf",
    icon: Scissors,
    tags: ["pdf", "split", "extract", "pages", "range"],
    status: "live",
    localProcessing: true,
    addedAt: 2,
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    slug: "compress-pdf",
    description: "Reduce PDF file size while keeping it readable.",
    category: "pdf",
    icon: Minimize2,
    tags: ["pdf", "compress", "shrink", "reduce", "size", "optimise"],
    popular: true,
    featured: true,
    status: "live",
    localProcessing: true,
    addedAt: 3,
  },
  {
    id: "pdf-to-image",
    name: "PDF to Images",
    slug: "pdf-to-image",
    description: "Turn PDF pages into PNG or JPG images.",
    category: "pdf",
    icon: FileImage,
    tags: ["pdf", "image", "png", "jpg", "convert", "export"],
    status: "live",
    localProcessing: true,
    addedAt: 4,
  },
  {
    id: "images-to-pdf",
    name: "Images to PDF",
    slug: "images-to-pdf",
    description: "Combine images into a single PDF document.",
    category: "pdf",
    icon: Images,
    tags: ["image", "pdf", "convert", "jpg", "png", "document"],
    status: "live",
    localProcessing: true,
    addedAt: 5,
  },

  /* -------------------------------------------------------------- IMAGE */
  {
    id: "image-compressor",
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Shrink JPG, PNG and WebP images with a quality slider.",
    category: "image",
    icon: ImageDown,
    tags: ["image", "compress", "jpg", "png", "webp", "optimise", "size"],
    popular: true,
    status: "live",
    localProcessing: true,
    addedAt: 6,
  },
  {
    id: "image-resizer",
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Resize images by width and height, with aspect lock.",
    category: "image",
    icon: Scaling,
    tags: ["image", "resize", "scale", "dimensions", "width", "height"],
    status: "live",
    localProcessing: true,
    addedAt: 7,
  },
  {
    id: "image-converter",
    name: "Image Converter",
    slug: "image-converter",
    description: "Convert images between JPG, PNG and WebP.",
    category: "image",
    icon: Repeat,
    tags: ["image", "convert", "jpg", "png", "webp", "format"],
    status: "live",
    localProcessing: true,
    addedAt: 8,
  },
  {
    id: "image-cropper",
    name: "Image Cropper",
    slug: "image-cropper",
    description: "Crop images freely or to a fixed aspect ratio.",
    category: "image",
    icon: Crop,
    tags: ["image", "crop", "trim", "aspect ratio", "square"],
    status: "live",
    localProcessing: true,
    addedAt: 9,
  },
  {
    id: "image-metadata",
    name: "Image Metadata Viewer",
    slug: "image-metadata",
    description: "Inspect EXIF and other metadata stored in an image.",
    category: "image",
    icon: Info,
    tags: ["image", "metadata", "exif", "camera", "gps", "inspect"],
    status: "live",
    localProcessing: true,
    addedAt: 10,
  },

  /* ---------------------------------------------------------- DEVELOPER */
  {
    id: "json-formatter",
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Format, validate and minify JSON with clear errors.",
    category: "developer",
    icon: Braces,
    tags: ["json", "format", "beautify", "validate", "pretty", "developer"],
    popular: true,
    featured: true,
    status: "live",
    localProcessing: true,
    addedAt: 11,
  },
  {
    id: "json-minifier",
    name: "JSON Minifier",
    slug: "json-minifier",
    description: "Strip whitespace from JSON to make it as small as possible.",
    category: "developer",
    icon: Minimize,
    tags: ["json", "minify", "compress", "whitespace", "developer"],
    status: "live",
    localProcessing: true,
    addedAt: 12,
  },
  {
    id: "base64",
    name: "Base64 Encoder / Decoder",
    slug: "base64",
    description: "Encode text to Base64 or decode it back.",
    category: "developer",
    icon: Binary,
    tags: ["base64", "encode", "decode", "convert", "developer"],
    status: "live",
    localProcessing: true,
    addedAt: 13,
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    slug: "uuid-generator",
    description: "Generate one or many RFC 4122 version 4 UUIDs.",
    category: "developer",
    icon: Fingerprint,
    tags: ["uuid", "guid", "generate", "random", "identifier", "developer"],
    status: "live",
    localProcessing: true,
    addedAt: 14,
  },
  {
    id: "timestamp",
    name: "Timestamp Converter",
    slug: "timestamp",
    description: "Convert between Unix timestamps and readable dates.",
    category: "developer",
    icon: Clock,
    tags: ["timestamp", "unix", "epoch", "date", "time", "convert"],
    status: "live",
    localProcessing: true,
    addedAt: 15,
  },

  /* ----------------------------------------------------------------- QR */
  {
    id: "qr-generator",
    name: "QR Code Generator",
    slug: "qr-generator",
    description: "Create QR codes for links, text, email, phone and Wi-Fi.",
    category: "qr",
    icon: QrCode,
    tags: ["qr", "qr code", "generate", "url", "wifi", "barcode"],
    popular: true,
    featured: true,
    status: "live",
    localProcessing: true,
    addedAt: 16,
  },

  /* --------------------------------------------------- EVERYDAY / OTHER */
  {
    id: "password-generator",
    name: "Password Generator",
    slug: "password-generator",
    description: "Build strong random passwords with the options you choose.",
    category: "business",
    icon: KeyRound,
    tags: ["password", "generate", "random", "secure", "strong"],
    popular: true,
    status: "live",
    localProcessing: true,
    addedAt: 17,
  },
  {
    id: "word-counter",
    name: "Word Counter",
    slug: "word-counter",
    description: "Count words, characters, sentences and reading time.",
    category: "student",
    icon: Type,
    tags: ["word", "count", "characters", "text", "essay", "reading time"],
    popular: true,
    status: "live",
    localProcessing: true,
    addedAt: 18,
  },
  {
    id: "percentage-calculator",
    name: "Percentage Calculator",
    slug: "percentage-calculator",
    description: "Work out percentages, shares and increases or decreases.",
    category: "calculators",
    icon: Percent,
    tags: ["percentage", "percent", "calculate", "increase", "decrease", "maths"],
    popular: true,
    status: "live",
    localProcessing: true,
    addedAt: 19,
  },
  {
    id: "age-calculator",
    name: "Age Calculator",
    slug: "age-calculator",
    description: "Calculate an exact age in years, months and days.",
    category: "calculators",
    icon: CalendarDays,
    tags: ["age", "birthday", "date", "calculate", "years", "days"],
    status: "live",
    localProcessing: true,
    addedAt: 20,
  },

  /* ------------------------------------------------------------- HEALTH */
  {
    id: "period-calculator",
    name: "Period & Cycle Calculator",
    slug: "period-calculator",
    description: "Estimate your next periods and fertile window.",
    category: "health",
    icon: Droplets,
    tags: ["period", "cycle", "menstrual", "ovulation", "fertility", "women"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 21,
  },
  {
    id: "due-date-calculator",
    name: "Pregnancy Due Date Calculator",
    slug: "due-date-calculator",
    description: "Estimate a due date and see how far along you are.",
    category: "health",
    icon: Baby,
    tags: ["pregnancy", "due date", "weeks", "trimester", "baby", "women"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 22,
  },
  {
    id: "bmi-calculator",
    name: "BMI Calculator",
    slug: "bmi-calculator",
    description: "Check BMI and the healthy weight range for your height.",
    category: "health",
    icon: Activity,
    tags: ["bmi", "weight", "height", "health", "body mass index"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 23,
  },

  /* ------------------------------------------------------------ STUDENT */
  {
    id: "gpa-calculator",
    name: "GPA & CGPA Calculator",
    slug: "gpa-calculator",
    description: "Work out semester GPA and cumulative CGPA on a 5.0 or 4.0 scale.",
    category: "student",
    icon: GraduationCap,
    tags: ["gpa", "cgpa", "grade", "university", "student", "class of degree"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 24,
  },

  /* ---------------------------------------------------------------- WEB */
  {
    id: "meta-tag-generator",
    name: "Meta Tag Generator",
    slug: "meta-tag-generator",
    description: "Build title, description, Open Graph and X tags with a live preview.",
    category: "web",
    icon: Code2,
    tags: ["meta", "seo", "open graph", "og", "twitter", "html", "head"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 25,
  },

  /* ------------------------------------------------- STUDENT (batch 2) */
  {
    id: "citation-generator",
    name: "Citation Generator",
    slug: "citation-generator",
    description: "Build APA, MLA, Harvard and Chicago references.",
    category: "student",
    icon: Quote,
    tags: ["citation", "reference", "apa", "mla", "harvard", "chicago", "bibliography"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 26,
  },
  {
    id: "grade-calculator",
    name: "Grade Calculator",
    slug: "grade-calculator",
    description: "See your current grade and what you need on what's left.",
    category: "student",
    icon: Target,
    tags: ["grade", "marks", "exam", "weighted", "average", "student", "final"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 27,
  },
  {
    id: "text-case-converter",
    name: "Text Case Converter",
    slug: "text-case-converter",
    description: "Convert text to title, sentence, camel, snake and kebab case.",
    category: "student",
    icon: CaseSensitive,
    tags: ["case", "text", "title case", "camelcase", "snake_case", "kebab", "uppercase"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 28,
  },
  {
    id: "readability-checker",
    name: "Readability Checker",
    slug: "readability-checker",
    description: "Score your writing and find the sentences slowing it down.",
    category: "student",
    icon: BookOpen,
    tags: ["readability", "flesch", "grade level", "writing", "essay", "clarity"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 29,
  },
  {
    id: "hidden-text-scanner",
    name: "Hidden Text & Prompt Injection Scanner",
    slug: "hidden-text-scanner",
    description: "Find invisible characters and hidden instructions in text or PDFs.",
    category: "student",
    icon: ScanSearch,
    tags: ["hidden text", "prompt injection", "invisible", "unicode", "pdf", "security", "zero width"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 30,
  },

  /* ------------------------------------------------ women's health guides */
  {
    id: "postpartum-guide",
    name: "Postpartum Care Guide",
    slug: "postpartum-guide",
    description: "Essential information and tips for recovery after childbirth.",
    category: "health",
    icon: HeartHandshake,
    tags: ["postpartum", "postnatal", "recovery", "childbirth", "fourth trimester", "new mother"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 31,
  },
  {
    id: "pregnancy-shopping-list",
    name: "Pregnancy Shopping List",
    slug: "pregnancy-shopping-list",
    description: "Trimester-by-trimester checklist of what to buy before the baby arrives.",
    category: "health",
    icon: ShoppingBasket,
    tags: [
      "pregnancy",
      "baby",
      "shopping list",
      "hospital bag",
      "newborn",
      "checklist",
      "trimester",
      "registry",
    ],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 32,
  },

  {
    id: "ovulation-calculator",
    name: "Ovulation Calculator",
    slug: "ovulation-calculator",
    description: "Find your fertile window and estimated ovulation day.",
    category: "health",
    icon: Egg,
    tags: ["ovulation", "fertile window", "conception", "ttc", "cycle", "fertility"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 38,
  },
  {
    id: "water-intake-calculator",
    name: "Water Intake Calculator",
    slug: "water-intake-calculator",
    description: "Work out roughly how much fluid to drink each day.",
    category: "health",
    icon: Droplets,
    tags: ["water", "hydration", "fluid", "drink", "litres", "health"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 39,
  },
  {
    id: "calorie-calculator",
    name: "Calorie & TDEE Calculator",
    slug: "calorie-calculator",
    description: "Find your BMR and daily calorie needs for your goal.",
    category: "health",
    icon: Flame,
    tags: ["calories", "bmr", "tdee", "metabolism", "weight", "macros", "diet"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 40,
  },

  /* ------------------------------------------------------------- business */
  {
    id: "invoice-generator",
    name: "Invoice Generator",
    slug: "invoice-generator",
    description: "Create a professional invoice PDF and download it instantly.",
    category: "business",
    icon: FileSpreadsheet,
    tags: ["invoice", "billing", "pdf", "freelance", "small business", "tax"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 33,
  },
  {
    id: "receipt-generator",
    name: "Receipt Generator",
    slug: "receipt-generator",
    description: "Produce a clean receipt PDF confirming a payment you have received.",
    category: "business",
    icon: Receipt,
    tags: ["receipt", "payment", "proof of payment", "pdf", "business", "sales"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 34,
  },
  {
    id: "business-card-maker",
    name: "Business Card Maker",
    slug: "business-card-maker",
    description: "Design a business card and export it print-ready as PNG or PDF.",
    category: "business",
    icon: CreditCard,
    tags: ["business card", "design", "print", "pdf", "png", "branding"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 35,
  },
  {
    id: "certificate-generator",
    name: "Certificate Generator",
    slug: "certificate-generator",
    description: "Design certificates with templates, logos, signatures and batch CSV export.",
    category: "business",
    icon: Award,
    tags: [
      "certificate",
      "award",
      "completion",
      "training",
      "pdf",
      "course",
      "batch",
      "csv",
      "template",
      "diploma",
    ],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 36,
  },

  /* ------------------------------------------------------------------ web */
  {
    id: "ip-location-checker",
    name: "IP Location Checker",
    slug: "ip-location-checker",
    description: "Look up the approximate location and network behind an IP address.",
    category: "web",
    icon: MapPin,
    tags: ["ip", "geolocation", "location", "isp", "asn", "network", "my ip"],
    popular: true,
    isNew: true,
    status: "live",
    addedAt: 37,
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    slug: "slug-generator",
    description: "Turn titles into clean, readable URL slugs.",
    category: "web",
    icon: Link2,
    tags: ["slug", "url", "permalink", "seo", "kebab case", "transliterate"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 41,
  },
  {
    id: "color-contrast-checker",
    name: "Colour Contrast Checker",
    slug: "color-contrast-checker",
    description: "Check text contrast against WCAG AA and AAA, with a fix suggested.",
    category: "web",
    icon: Contrast,
    tags: ["contrast", "wcag", "accessibility", "a11y", "colour", "color", "ratio"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 42,
  },
  {
    id: "favicon-generator",
    name: "Favicon Generator",
    slug: "favicon-generator",
    description: "Make every favicon size from one image, with the HTML to match.",
    category: "web",
    icon: AppWindow,
    tags: ["favicon", "icon", "apple touch icon", "pwa", "manifest", "png"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 43,
  },
  {
    id: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum-generator",
    description: "Placeholder text in Latin or plain English, with HTML if you want it.",
    category: "web",
    icon: AlignLeft,
    tags: ["lorem ipsum", "placeholder", "dummy text", "filler", "mockup", "design"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 44,
  },
  {
    id: "url-encoder",
    name: "URL Encoder / Decoder",
    slug: "url-encoder",
    description: "Percent-encode or decode URLs, and break one into its parts.",
    category: "web",
    icon: Link,
    tags: ["url", "encode", "decode", "percent encoding", "query string", "uri"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 45,
  },
  {
    id: "robots-txt-generator",
    name: "robots.txt Generator",
    slug: "robots-txt-generator",
    description: "Build a robots.txt file, with AI-crawler opt-out if you want it.",
    category: "web",
    icon: Bot,
    tags: ["robots.txt", "seo", "crawler", "sitemap", "googlebot", "gptbot", "ai"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 46,
  },
  {
    id: "study-timer",
    name: "Study Timer",
    slug: "study-timer",
    description: "A Pomodoro timer with adjustable focus and break lengths.",
    category: "student",
    icon: Timer,
    tags: ["pomodoro", "timer", "study", "focus", "productivity", "revision"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 47,
  },
  {
    id: "random-picker",
    name: "Random Picker",
    slug: "random-picker",
    description: "Pick a winner, shuffle an order, make teams or roll a number.",
    category: "student",
    icon: Shuffle,
    tags: ["random", "picker", "raffle", "shuffle", "teams", "draw", "dice"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 48,
  },
  {
    id: "prompt-generator",
    name: "AI Prompt Generator",
    slug: "prompt-generator",
    description: "Build a structured prompt from role, task, context and constraints.",
    category: "ai",
    icon: Sparkles,
    tags: ["prompt", "ai", "chatgpt", "claude", "prompt engineering", "llm"],
    popular: true,
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 49,
  },
  {
    id: "prompt-library",
    name: "AI Prompt Library",
    slug: "prompt-library",
    description: "Twelve prompt templates that work, ready to fill in and copy.",
    category: "ai",
    icon: Library,
    tags: ["prompt", "templates", "ai", "library", "chatgpt", "claude", "examples"],
    isNew: true,
    status: "live",
    localProcessing: true,
    addedAt: 50,
  },
];

/* ------------------------------------------------------------- helpers */

export const getTool = (slug: string) => TOOLS.find((t) => t.slug === slug);

export const liveTools = () => TOOLS.filter((t) => t.status === "live");

export const toolsByCategory = (category: CategoryId) =>
  TOOLS.filter((t) => t.category === category);

export const countByCategory = (category: CategoryId) =>
  toolsByCategory(category).length;

export const popularTools = () => TOOLS.filter((t) => t.popular);

export const newTools = () => TOOLS.filter((t) => t.isNew);

/**
 * Search across name, description, category and tags (§20). Ranked so a name
 * match beats a tag match, which beats a description match.
 */
export const searchTools = (query: string, pool: Tool[] = TOOLS): Tool[] => {
  const q = query.trim().toLowerCase();
  if (!q) return pool;

  const scored = pool
    .map((tool) => {
      const name = tool.name.toLowerCase();
      let score = 0;

      if (name === q) score = 100;
      else if (name.startsWith(q)) score = 80;
      else if (name.includes(q)) score = 60;
      else if (tool.tags.some((t) => t === q)) score = 50;
      else if (tool.tags.some((t) => t.includes(q))) score = 35;
      else if (tool.category.includes(q)) score = 25;
      else if (tool.description.toLowerCase().includes(q)) score = 20;

      return { tool, score };
    })
    .filter((r) => r.score > 0)
    .sort((a, b) => b.score - a.score || a.tool.name.localeCompare(b.tool.name));

  return scored.map((r) => r.tool);
};
